### ISSUE TITLE
PlayerSpawn not working

### ISSUE THREAD

**Issue by Neshiro** [seagemgames/saismee-addons#2]
To whoever will read this, hello.

I tried to use the PlayerSpawn item in this pack but no matter where I place it in my map, I always spawn at the original entry door.
If anyone knows how to use this item properly, I would be grateful to know how.

Have a nice day and thanks for reading.

**Comment by saismeesaimonsaimes** [comment]
Try removing the original entry door. Do note, however, the player spawn does not enable the observation room light, nor does it auto-drop cubes.

**Comment by Neshiro** [comment]
I already did that, by checking the "Unlock default items" setting in the BeeMod, but the entry door refuses to be deleted.

Also, if I ever add another entry door, this one too refuses to get deleted and I find myself with two entry doors. However, this issue is probably unrelated to your package.

**Comment by saismeesaimonsaimes** [comment]
@Neshiro "Unlock Default Items" is broken in BEEmod 4.39.2. You'll have to manually edit the editoritems.txt at `Portal 2\portal2_dlc2\scripts`, find the entry door and set `Deletable` to `1`.
